# syntax=docker/dockerfile:1.7
FROM rust:1.98.1-bookworm AS build
WORKDIR /src
COPY . .
RUN cargo build --locked --release --bin inferqos-fake-provider
FROM gcr.io/distroless/cc-debian12:nonroot
COPY --from=build /src/target/release/inferqos-fake-provider /usr/local/bin/fake-provider
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/fake-provider"]

