[package]
name = "inferqos-identity"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
http.workspace = true
inferqos-config.workspace = true
inferqos-core.workspace = true
ipnet.workspace = true
jsonwebtoken.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
